/* =========================================================
   storage.js — Cloud data layer (Firebase Firestore)
   AsiaformS Digital Order Confirmation App

   Orders live in a Firestore collection ("orders") so a link
   generated by a representative opens correctly on the
   customer's OWN device/browser — not just the one that
   created it. See README.md for the 5-minute setup.

   The order-creation DRAFT (autosave-while-typing) still uses
   localStorage — that's just in-progress scratch state for the
   rep's own browser and doesn't need to be shared.
   ========================================================= */

const AF_DRAFT_KEY = 'af_draft_order';

let _db = null;
let _firebaseError = null;

/** True once js/firebase-config.js has real (non-placeholder) keys */
function isFirebaseConfigured() {
  const cfg = window.FIREBASE_CONFIG;
  return !!(cfg && cfg.apiKey && !String(cfg.apiKey).startsWith('PASTE_'));
}

function initFirebase() {
  if (_db || _firebaseError) return;
  try {
    if (!isFirebaseConfigured()) {
      _firebaseError = 'not-configured';
      return;
    }
    firebase.initializeApp(window.FIREBASE_CONFIG);
    _db = firebase.firestore();
    // Local cache so the dashboard still feels instant and works offline;
    // syncs automatically once back online.
    _db.enablePersistence({ synchronizeTabs: true }).catch(() => {});
  } catch (e) {
    console.error('Firebase init failed', e);
    _firebaseError = e.message || 'init-failed';
  }
}
initFirebase();

/** Shows a one-time setup banner if Firebase hasn't been configured yet */
function renderFirebaseSetupNotice() {
  if (isFirebaseConfigured()) return;
  const el = document.createElement('div');
  el.style.cssText =
    'position:fixed;top:0;left:0;right:0;z-index:400;background:#C98A12;color:#fff;padding:10px 16px;font:600 13px Inter,sans-serif;text-align:center;';
  el.innerHTML =
    'Cloud backend not configured yet — edit <code>js/firebase-config.js</code> with your Firebase project keys. See README.md.';
  document.body.appendChild(el);
}
document.addEventListener('DOMContentLoaded', renderFirebaseSetupNotice);

function ordersCollection() {
  if (!_db) throw new Error('Firebase is not configured. Edit js/firebase-config.js — see README.md.');
  return _db.collection('orders');
}

const Storage = {
  /** Return all orders, newest first */
  async getOrders() {
    try {
      const snap = await ordersCollection().orderBy('createdAt', 'desc').get();
      return snap.docs.map((d) => d.data());
    } catch (e) {
      console.error('Storage.getOrders failed', e);
      showToast?.('Could not load orders from the cloud', 'error');
      return [];
    }
  },

  /** Get a single order by id */
  async getOrderById(id) {
    try {
      const doc = await ordersCollection().doc(id).get();
      return doc.exists ? doc.data() : null;
    } catch (e) {
      console.error('Storage.getOrderById failed', e);
      return null;
    }
  },

  /** Insert or update an order (matched by id) */
  async saveOrder(order) {
    await ordersCollection().doc(order.id).set(order);
    return order;
  },

  /** Delete an order by id */
  async deleteOrder(id) {
    await ordersCollection().doc(id).delete();
  },

  /** Update just the status (+ approval metadata) of an order */
  async updateStatus(id, status, extra = {}) {
    const order = await this.getOrderById(id);
    if (!order) return null;
    order.status = status;
    Object.assign(order, extra);
    await this.saveOrder(order);
    return order;
  },

  /** Duplicate an order as a fresh Pending draft with a new id */
  async duplicateOrder(id) {
    const original = await this.getOrderById(id);
    if (!original) return null;
    const copy = JSON.parse(JSON.stringify(original));
    copy.id = generateId();
    copy.createdAt = new Date().toISOString();
    copy.status = 'Pending';
    copy.approval = { agreed: false, approvedAt: null };
    await this.saveOrder(copy);
    return copy;
  },

  /** Dashboard summary counts */
  async getStats() {
    const orders = await this.getOrders();
    return {
      total: orders.length,
      pending: orders.filter((o) => o.status === 'Pending').length,
      approved: orders.filter((o) => o.status === 'Approved').length,
      rejected: orders.filter((o) => o.status === 'Rejected').length,
    };
  },

  /** Search + filter helper used by the dashboard */
  async queryOrders({ term = '', status = 'All' } = {}) {
    let orders = await this.getOrders();
    if (status !== 'All') orders = orders.filter((o) => o.status === status);
    if (term.trim()) {
      const t = term.trim().toLowerCase();
      orders = orders.filter((o) => {
        const hay = [
          o.customer?.name,
          o.customer?.mobile,
          o.customer?.gstin,
          o.topSection?.repName,
          shortOrderNumber(o.id),
        ]
          .join(' ')
          .toLowerCase();
        return hay.includes(t);
      });
    }
    return orders;
  },

  /**
   * Subscribe to realtime order changes (e.g. customer approving on their
   * own phone while the rep's dashboard is open). Returns an unsubscribe
   * function. No-ops quietly if Firebase isn't configured yet.
   */
  onOrdersChange(callback) {
    if (!isFirebaseConfigured()) return () => {};
    try {
      return ordersCollection()
        .orderBy('createdAt', 'desc')
        .onSnapshot(
          (snap) => callback(snap.docs.map((d) => d.data())),
          (err) => console.error('onOrdersChange error', err)
        );
    } catch (e) {
      return () => {};
    }
  },

  /* ---------------- Draft autosave (create-order form, local only) ---------------- */

  saveDraft(data) {
    localStorage.setItem(AF_DRAFT_KEY, JSON.stringify({ data, savedAt: new Date().toISOString() }));
  },

  getDraft() {
    try {
      const raw = localStorage.getItem(AF_DRAFT_KEY);
      return raw ? JSON.parse(raw) : null;
    } catch (e) {
      return null;
    }
  },

  clearDraft() {
    localStorage.removeItem(AF_DRAFT_KEY);
  },

  /** Build a blank order skeleton matching the paper form structure */
  blankOrder() {
    return {
      id: generateId(),
      createdAt: new Date().toISOString(),
      status: 'Pending',
      topSection: {
        common: false,
        newCustomer: false,
        regularCustomer: false,
        newProduct: false,
        oldDesignFSBS: false,
        newDesignFSBS: false,
        oldDesignNewFilm: false,
        date: new Date().toISOString().slice(0, 10),
        repName: '',
      },
      customer: {
        name: '',
        address: '',
        gstin: '',
        mailId: '',
        contactPerson: '',
        designation: '',
        mobile: '',
        deliveryAddressType: 'Same',
        deliveryAddress: '',
      },
      products: [blankProduct()],
      sticker: {
        numberingDetails: '',
        ups: '',
        coreSize: '',
        qtyRoll: '',
        offsetType: false,
        barcodeType: false,
        windingDirection: '',
      },
      rate: {
        qty: '',
        rate: '',
        taxableAmount: '',
        gstPercent: '',
        gstValue: '',
        totalValue: '',
        approxValue: '',
      },
      transport: {
        freight: 'To Pay',
        transport: '',
        deliveryPeriod: '',
        paymentTerms: '',
        lastBillDate: '',
        amtRecdDate: '',
      },
      bottomCheck: {
        orderFormApproval: false,
        waGroup: false,
        orderSubmissionWA: false,
      },
      remarks: '',
      signatures: {
        representative: '',
        designer: '',
        specialApproval: '',
        coordinator: '',
      },
      approval: {
        agreed: false,
        approvedAt: null,
      },
    };
  },
};
